var friends = [{
    "name":"Chandler",
    "photo":"https://vignette.wikia.nocookie.net/friends/images/c/cc/Square_Chandler.jpg",
    "scores":[
        2,
        3,
        4,
        4,
        3,
        3,
        1,
        1,
        2,
        2
      ]
  },
  {
    "name":"Sean",
    "photo":"https://www.designzzz.com/wp-content/uploads/2012/12/freestock_image_by_goldman555-d495w4s.jpg",
    "scores":[
        5,
        5,
        4,
        4,
        2,
        3,
        2,
        4,
        4,
        1
      ]
  },
  {
    "name":"Stella",
    "photo":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTACMl9I3lcMYfz6RKTnHFsm6cGRel0IPA_PkwT7mn5GriUgSWiGw",
    "scores":[
        5,
        4,
        3,
        5,
        5,
        5,
        5,
        1,
        2,
        3
      ]
  },
  {
    "name":"Giulia",
    "photo":"https://thumb1.shutterstock.com/mosaic_250/2936380/648907024/stock-photo-portrait-of-cheerful-beautiful-woman-with-trendy-hairdo-having-dark-charming-eyes-and-engaging-648907024.jpg",
    "scores":[
        4,
        4,
        4,
        4,
        2,
        2,
        2,
        5,
        5,
        5
      ]
  },
  {
    "name":"George",
    "photo":"https://entropymag.org/wp-content/uploads/2014/10/stock5.jpg",
    "scores":[
        3,
        3,
        3,
        1,
        1,
        3,
        2,
        5,
        5,
        5
      ]
  },
]

module.exports = friends;